In [9]:
import numpy as np

In [12]:
#### 3. Create a null vector of size 10 (★☆☆)
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#### 4. How to find the memory size of any array (★☆☆) 

memory_size = arr.nbytes
print("Memory (in bytes) :", memory_size)

Memory (in bytes) : 80


In [17]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

rev_vec = vec[::-1]
print(rev_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
mat = np.diag(np.arange(1, 5), k=-1)
print(mat)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
mat = np.zeros((8, 8), dtype=int)
mat[1::2, ::2] = 1
mat[::2, 1::2] = 1
print(mat)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
index_ = np.unravel_index(100, (6, 7, 8))
print(index_)


(np.int64(1), np.int64(5), np.int64(4))


In [13]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
mat = np.tile([[0, 1], [1, 0]], (4, 4))
print(mat)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
mat = np.random.rand(5, 5)
mat = (mat - np.min(mat)) / (np.max(mat) - np.min(mat))
print(mat)


[[1.         0.39189764 0.37592135 0.22101654 0.16778324]
 [0.15775681 0.29763041 0.83767367 0.02178321 0.59567078]
 [0.80235378 0.50357407 0.89429983 0.65371641 0.67733626]
 [0.49106558 0.09780466 0.21020177 0.03421071 0.14288834]
 [0.74446978 0.         0.21531329 0.55711265 0.97870147]]


In [18]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
mat_1 = np.random.rand(5, 3)
mat_2= np.random.rand(3, 2)
res = np.dot(mat_1, mat_2)
print(res)



[[0.87906536 0.76816487]
 [0.47726114 0.85277038]
 [0.33055497 0.57457112]
 [0.31258215 0.4661878 ]
 [0.25453405 0.47795151]]


In [19]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]
